/**
 * System Log client — vendored from byrdson-logging/clients/qb-logger.ts.
 *
 * SERVER ONLY. This repo does not carry the `server-only` package (neither does
 * lib/quickbase.ts, which reads the same token), so that is a convention here
 * rather than a build error: never import this from a client component.
 *
 * Writes straight to the Quickbase System Log app over the REST API. Drop this in
 * the app's lib/ folder; most of our apps already hold a Quickbase user token, so
 * wiring is usually two env vars, not three:
 *
 *   QB_USER_TOKEN   already set in every app that talks to Quickbase
 *   LOG_SYSTEM      this app's System Key from the Systems table, e.g. "subs-award"
 *   LOG_COMPONENT   optional default sub-part
 *   QB_LOG_TOKEN    optional — a separate token if you do not want to reuse the above
 *
 * Without a token every function here is a no-op that still writes the line to
 * stdout, so this is safe to merge and deploy before anything else is ready.
 * Logging never throws: a failed log line must not fail the operation it describes.
 */

// --- schema -----------------------------------------------------------------
// Field ids, not labels — Quickbase addresses records by fid. Generated by
// scripts/provision-qb.mjs; test/schema-drift.test.mjs fails if this drifts.

const QB = {
  realm: "byrdsonservices.quickbase.com",
  app: "bwde929pp",
  tables: {
    activity: "bwde94zt6",
    errors: "bwde946wy",
    runs: "bwde95dxe",
    audit: "bwde95jxi",
    systems: "bwde9292e",
  },
  /** Identical across all four log tables, which is why one writer can fill any of them. */
  env: {
    time: 6, system: 7, component: 8, environment: 9, event: 10, message: 11,
    actor: 12, source: 13, correlation: 14, link: 15, details: 16, logId: 17,
  },
  activity: { level: 18, status: 19, entityType: 20, entityId: 21, durationMs: 22, items: 23, runId: 24 },
  errors: {
    severity: 18, errorType: 19, entityType: 20, entityId: 21, runId: 22, stack: 23,
    fingerprint: 24, occurrences: 25, firstSeen: 26, lastSeen: 27, triage: 28,
    assignedTo: 29, resolvedAt: 30, notes: 31,
  },
  runs: {
    runKey: 18, startedAt: 19, endedAt: 20, trigger: 21, status: 22, durationMs: 23,
    itemsIn: 24, itemsOk: 25, itemsFailed: 26,
  },
  audit: {
    action: 18, outcome: 19, targetTable: 20, targetId: 21, changedFields: 22,
    before: 23, after: 24, ip: 25, userAgent: 26,
  },
} as const;

export type LogLevel = "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL";
export type LogStatus = "success" | "failure" | "partial" | "skipped" | "running";

export type LogEvent = {
  /** Dotted event name, e.g. "award.sent", "po.created", "payroll.run". */
  event: string;
  level?: LogLevel;
  status?: LogStatus;
  message?: string;
  component?: string;
  system?: string;
  entity?: { type?: string; id?: string | number };
  /** Who did it — the email, not the display name. */
  actor?: string;
  durationMs?: number;
  items?: number;
  correlationId?: string;
  link?: string;
  /** Anything else worth having later. Never put secrets or full PII in here. */
  details?: Record<string, unknown>;
};

export type AuditEvent = {
  action: string;
  actor: string;
  outcome: "ok" | "denied" | "error";
  target?: { table?: string; recordId?: string | number };
  changedFields?: string[];
  before?: unknown;
  after?: unknown;
  ip?: string;
  userAgent?: string;
  correlationId?: string;
  details?: Record<string, unknown>;
};

const REALM = process.env.QB_REALM || QB.realm;
const TOKEN = process.env.QB_LOG_TOKEN || process.env.QB_USER_TOKEN || "";
const SYSTEM = process.env.LOG_SYSTEM || "vendor-portal";
const COMPONENT = process.env.LOG_COMPONENT || "";
const ENVIRONMENT =
  process.env.LOG_ENV || process.env.VERCEL_ENV || (process.env.NODE_ENV === "production" ? "prod" : "dev");
const TIMEOUT_MS = Number(process.env.LOG_TIMEOUT_MS || 4000);
const DROP_LEVELS = (process.env.LOG_DROP_LEVELS || "DEBUG").split(/[,\s]+/).filter(Boolean);

export const loggingEnabled = Boolean(TOKEN);

// --- value coercion ---------------------------------------------------------
// Quickbase caps a plain text field at 255 characters and rejects the whole write
// if one value is over. Truncating here is the difference between a slightly short
// message and no log line at all.

const TEXT_MAX = 255;
const LONG_MAX = 8000;

const clip = (v: unknown, max: number): string => {
  if (v === null || v === undefined) return "";
  const s = typeof v === "string" ? v : safeJson(v);
  return s.length > max ? s.slice(0, max - 12) + "…[truncated]" : s;
};

function safeJson(v: unknown): string {
  try {
    return JSON.stringify(v) ?? "";
  } catch {
    return String(v);
  }
}

/** A URL field rejects anything that is not a URL, so only send real ones. */
const asUrl = (v?: string): string => (v && /^https?:\/\//i.test(v) ? clip(v, TEXT_MAX) : "");

type Rec = Record<number, { value: unknown }>;

function put(rec: Rec, fid: number, value: unknown, max = TEXT_MAX) {
  if (value === null || value === undefined || value === "") return;
  if (typeof value === "number") {
    if (Number.isFinite(value)) rec[fid] = { value };
    return;
  }
  if (typeof value === "boolean") {
    rec[fid] = { value };
    return;
  }
  const s = clip(value, max);
  if (s) rec[fid] = { value: s };
}

async function write(table: string, data: Rec[], mergeFieldId?: number): Promise<boolean> {
  const line = safeJson({ table, rows: data.length, first: data[0] });
  if (!loggingEnabled) {
    console.log(`LOG(disabled) ${line}`);
    return false;
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch("https://api.quickbase.com/v1/records", {
      method: "POST",
      headers: {
        "QB-Realm-Hostname": REALM,
        Authorization: `QB-USER-TOKEN ${TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ to: table, data, ...(mergeFieldId ? { mergeFieldId } : {}) }),
      signal: controller.signal,
    });
    const body = (await res.json().catch(() => ({}))) as {
      metadata?: { lineErrors?: Record<string, string[]> };
      message?: string;
      description?: string;
    };
    if (!res.ok) {
      console.error(`[log] quickbase ${res.status}: ${body.description || body.message || ""} :: ${line}`);
      return false;
    }
    const lineErrors = body.metadata?.lineErrors;
    if (lineErrors && Object.keys(lineErrors).length) {
      console.error(`[log] quickbase rejected rows: ${safeJson(lineErrors)} :: ${line}`);
      return false;
    }
    return true;
  } catch (err) {
    console.error(`[log] quickbase unreachable: ${(err as Error).message} :: ${line}`);
    return false;
  } finally {
    clearTimeout(timer);
  }
}

function envelope(ev: LogEvent, now: string): Rec {
  const rec: Rec = {};
  put(rec, QB.env.time, now);
  put(rec, QB.env.system, ev.system || SYSTEM);
  put(rec, QB.env.component, ev.component ?? COMPONENT);
  put(rec, QB.env.environment, ENVIRONMENT);
  put(rec, QB.env.event, ev.event);
  put(rec, QB.env.message, ev.message, LONG_MAX);
  put(rec, QB.env.actor, ev.actor);
  put(rec, QB.env.source, "vercel");
  put(rec, QB.env.correlation, ev.correlationId);
  put(rec, QB.env.link, asUrl(ev.link));
  put(rec, QB.env.details, ev.details ? safeJson(ev.details) : "", LONG_MAX);
  put(rec, QB.env.logId, newId());
  return rec;
}

function newId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

/**
 * Digits are stripped so "record 8123 failed" and "record 8124 failed" share a
 * fingerprint — it is the same bug either way, and the Errors table counts rather
 * than repeats it.
 */
function fingerprint(system: string, component: string, errorType: string, message: string): string {
  const basis = `${system}|${component}|${errorType}|${message.replace(/\d+/g, "#").slice(0, 160)}`;
  let h1 = 0x811c9dc5;
  let h2 = 0x01000193;
  for (let i = 0; i < basis.length; i++) {
    h1 = Math.imul(h1 ^ basis.charCodeAt(i), 0x01000193) >>> 0;
    h2 = Math.imul(h2 + basis.charCodeAt(i), 0x85ebca6b) >>> 0;
  }
  return (h1.toString(16) + h2.toString(16)).slice(0, 12);
}

// --- public API -------------------------------------------------------------

/** One Activity record. Await it — a floating promise on a serverless function
 *  is cut off the moment the response returns, taking the log line with it. */
export async function log(ev: LogEvent): Promise<void> {
  if (DROP_LEVELS.includes((ev.level || "INFO").toUpperCase())) return;
  const now = new Date().toISOString();
  const rec = envelope(ev, now);
  put(rec, QB.activity.level, (ev.level || "INFO").toUpperCase());
  put(rec, QB.activity.status, ev.status || "success");
  put(rec, QB.activity.entityType, ev.entity?.type);
  put(rec, QB.activity.entityId, ev.entity?.id);
  put(rec, QB.activity.durationMs, ev.durationMs);
  put(rec, QB.activity.items, ev.items);
  await write(QB.tables.activity, [rec]);
}

/** Several Activity records in one request. Use when a batch wants a row per item. */
export async function logBatch(events: LogEvent[]): Promise<void> {
  const now = new Date().toISOString();
  const rows = events
    .filter((ev) => !DROP_LEVELS.includes((ev.level || "INFO").toUpperCase()))
    .map((ev) => {
      const rec = envelope(ev, now);
      put(rec, QB.activity.level, (ev.level || "INFO").toUpperCase());
      put(rec, QB.activity.status, ev.status || "success");
      put(rec, QB.activity.entityType, ev.entity?.type);
      put(rec, QB.activity.entityId, ev.entity?.id);
      put(rec, QB.activity.durationMs, ev.durationMs);
      put(rec, QB.activity.items, ev.items);
      return rec;
    });
  if (rows.length) await write(QB.tables.activity, rows);
}

/**
 * One Errors record. Repeats inside the dedupe window bump the occurrence count on
 * the existing record instead of adding another, so a loop costs one row.
 */
export async function logError(
  err: unknown,
  ev: Omit<LogEvent, "event"> & { event?: string } = {},
): Promise<void> {
  const e = err instanceof Error ? err : new Error(String(err));
  const now = new Date().toISOString();
  const system = ev.system || SYSTEM;
  const component = ev.component ?? COMPONENT;
  const message = ev.message || e.message || "(no message)";
  const errorType = e.name || "Error";
  const fp = fingerprint(system, component, errorType, message);

  if (loggingEnabled && (await bumpExisting(fp, now, message))) return;

  const rec = envelope({ ...ev, event: ev.event || "unhandled.error", system, component, message }, now);
  put(rec, QB.errors.severity, (ev.level || "ERROR").toUpperCase() === "FATAL" ? "FATAL" : "ERROR");
  put(rec, QB.errors.errorType, errorType);
  put(rec, QB.errors.entityType, ev.entity?.type);
  put(rec, QB.errors.entityId, ev.entity?.id);
  put(rec, QB.errors.stack, (e.stack || "").split("\n").slice(0, 12).join("\n"), LONG_MAX);
  put(rec, QB.errors.fingerprint, fp);
  put(rec, QB.errors.occurrences, 1);
  put(rec, QB.errors.firstSeen, now);
  put(rec, QB.errors.lastSeen, now);
  put(rec, QB.errors.triage, "New");
  await write(QB.tables.errors, [rec]);
}

const DEDUPE_MINUTES = Number(process.env.LOG_DEDUPE_MINUTES || 60);

/** Returns true when an open record was updated and no new one is needed. */
async function bumpExisting(fp: string, now: string, message: string): Promise<boolean> {
  if (DEDUPE_MINUTES <= 0) return false;
  const since = new Date(Date.now() - DEDUPE_MINUTES * 60_000).toISOString();
  try {
    const res = await fetch("https://api.quickbase.com/v1/records/query", {
      method: "POST",
      headers: {
        "QB-Realm-Hostname": REALM,
        Authorization: `QB-USER-TOKEN ${TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: QB.tables.errors,
        select: [3, QB.errors.occurrences],
        where: `{${QB.errors.fingerprint}.EX.'${fp}'}AND{${QB.errors.lastSeen}.OAF.'${since}'}`,
        sortBy: [{ fieldId: QB.errors.lastSeen, order: "DESC" }],
        options: { top: 1 },
      }),
    });
    if (!res.ok) return false;
    const body = (await res.json()) as { data?: Array<Record<string, { value: unknown }>> };
    const hit = body.data?.[0];
    if (!hit) return false;

    const rid = Number(hit["3"]?.value);
    const count = Number(hit[String(QB.errors.occurrences)]?.value) || 1;
    const update: Rec = { 3: { value: rid } };
    put(update, QB.errors.occurrences, count + 1);
    put(update, QB.errors.lastSeen, now);
    put(update, QB.env.message, message, LONG_MAX);
    return await write(QB.tables.errors, [update]);
  } catch {
    // Dedupe is an optimisation. If the lookup fails, fall through and write a row.
    return false;
  }
}

/** Who changed what in a system of record. */
export async function logAudit(ev: AuditEvent): Promise<void> {
  const now = new Date().toISOString();
  const rec = envelope(
    { event: ev.action, actor: ev.actor, correlationId: ev.correlationId, details: ev.details },
    now,
  );
  put(rec, QB.audit.action, ev.action);
  put(rec, QB.audit.outcome, ev.outcome);
  put(rec, QB.audit.targetTable, ev.target?.table);
  put(rec, QB.audit.targetId, ev.target?.recordId);
  put(rec, QB.audit.changedFields, (ev.changedFields || []).join(", "), LONG_MAX);
  put(rec, QB.audit.before, ev.before ? safeJson(ev.before) : "", LONG_MAX);
  put(rec, QB.audit.after, ev.after ? safeJson(ev.after) : "", LONG_MAX);
  put(rec, QB.audit.ip, ev.ip);
  put(rec, QB.audit.userAgent, ev.userAgent, LONG_MAX);
  await write(QB.tables.audit, [rec]);
}

/**
 * A scheduled job or batch. Both calls carry the same Run Key, which is unique in
 * Quickbase, so the finish merges into the record the start created rather than
 * adding a second one.
 *
 *   const run = startRun({ component: "nightly-sync", trigger: "cron" });
 *   try { ...; await run.finish({ itemsOk: n }); }
 *   catch (e) { await run.fail(e); throw e; }
 */
export function startRun(opts: {
  component?: string;
  trigger?: string;
  system?: string;
  runId?: string;
  itemsIn?: number;
  message?: string;
} = {}) {
  const runId = opts.runId || newId();
  const startedAt = Date.now();
  const system = opts.system || SYSTEM;
  const component = opts.component ?? COMPONENT;

  const head = (now: string) => {
    const rec = envelope({ event: "run", system, component, message: opts.message }, now);
    put(rec, QB.runs.runKey, runId);
    return rec;
  };

  const startedAtIso = new Date(startedAt).toISOString();
  const start = (async () => {
    const rec = head(startedAtIso);
    put(rec, QB.runs.startedAt, startedAtIso);
    put(rec, QB.runs.trigger, opts.trigger || "manual");
    put(rec, QB.runs.status, "running");
    put(rec, QB.runs.itemsIn, opts.itemsIn);
    return write(QB.tables.runs, [rec], QB.runs.runKey);
  })();

  return {
    runId,
    async finish(result: {
      status?: LogStatus;
      itemsOk?: number;
      itemsFailed?: number;
      message?: string;
      link?: string;
      details?: Record<string, unknown>;
    } = {}) {
      await start;
      const now = new Date().toISOString();
      const rec = envelope(
        { event: "run", system, component, message: result.message, link: result.link, details: result.details },
        now,
      );
      put(rec, QB.runs.runKey, runId);
      put(rec, QB.runs.endedAt, now);
      put(rec, QB.runs.status, result.status || (result.itemsFailed ? "partial" : "success"));
      put(rec, QB.runs.durationMs, Date.now() - startedAt);
      put(rec, QB.runs.itemsOk, result.itemsOk);
      put(rec, QB.runs.itemsFailed, result.itemsFailed);
      await write(QB.tables.runs, [rec], QB.runs.runKey);
    },
    async fail(err: unknown, message?: string) {
      await start;
      const e = err instanceof Error ? err : new Error(String(err));
      const now = new Date().toISOString();
      const rec = envelope({ event: "run", system, component, message: message || e.message }, now);
      put(rec, QB.runs.runKey, runId);
      put(rec, QB.runs.endedAt, now);
      put(rec, QB.runs.status, "failure");
      put(rec, QB.runs.durationMs, Date.now() - startedAt);
      await write(QB.tables.runs, [rec], QB.runs.runKey);
      await logError(e, { system, component, event: "run.failed", details: { runId } });
    },
  };
}

export const __schema = QB;
